/*
 * Copyright (C) 2020 The zfoo Authors
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and limitations under the License.
 */

package com.zfoo.protocol.generate;

import com.zfoo.protocol.ProtocolManager;
import com.zfoo.protocol.collection.CollectionUtils;
import com.zfoo.protocol.exception.UnknownException;
import com.zfoo.protocol.registration.IProtocolRegistration;
import com.zfoo.protocol.registration.ProtocolAnalysis;
import com.zfoo.protocol.registration.ProtocolRegistration;
import com.zfoo.protocol.util.FileUtils;
import com.zfoo.protocol.util.ReflectionUtils;
import com.zfoo.protocol.util.StringUtils;

import java.io.IOException;
import java.lang.reflect.Field;
import java.util.*;
import java.util.function.Predicate;

import static com.zfoo.protocol.util.StringUtils.*;

/**
 * @author godotg
 */
public abstract class GenerateProtocolFile {

    /**
     * EN: Filter for generating protocol files. If no filter is set, all protocols will be generated by default.
     * Filter for protocol file generation; generates all protocols if no filter is set
     */
    public static Predicate<IProtocolRegistration> generateProtocolFilter = registration -> true;


    // -----------------------------------------------------------------------------------------------------------------
    /**
     * EN: The conventions for network packets are as follows:
     * 1. Client requests should end with "Request", and server responses should end with "Response".
     * 2. Internal server requests should end with "Ask", and internal server responses should end with "Answer".
     * 3. Server-initiated notifications to the client should end with "Notice".
     * 4. Common protocols should be placed in the common module.
     * 5. Internal protocols are not allowed to be used outside their scope.
     * <p>
     * Naming conventions for network packets:
     * 1. Client requests end with 'Request'; server responses end with 'Response'
     * 2. Internal server requests end with 'Ask'; internal responses end with 'Answer'
     * 3. Server-push notifications to clients end with 'Notice'
     * 4. Shared protocols go in the common module
     * 5. Internal protocol range must not 
     */
    public static final String NET_REQUEST_SUFFIX = "Request";
    public static final String NET_RESPONSE_SUFFIX = "Response";
    public static final String NET_NOTICE_SUFFIX = "Notice";

    public static final String NET_ASK_SUFFIX = "Ask";
    public static final String NET_ANSWER_SUFFIX = "Answer";

    public static final String NET_COMMON_PACKAGE = "common";
    public static final String NET_ATTACHMENT_PACKAGE = "attachment";

    public static final Predicate<IProtocolRegistration> DefaultNetGenerateProtocolFilter = it -> {
        var clazz = it.protocolConstructor().getDeclaringClass();
        var className = clazz.getSimpleName();
        if (className.endsWith(NET_ASK_SUFFIX) || className.endsWith(NET_ANSWER_SUFFIX)) {
            return false;
        }

        if (className.endsWith(NET_REQUEST_SUFFIX) || className.endsWith(NET_RESPONSE_SUFFIX) || className.endsWith(NET_NOTICE_SUFFIX)) {
            return true;
        }

        if (clazz.getPackageName().endsWith(NET_COMMON_PACKAGE) || clazz.getPackageName().endsWith(NET_ATTACHMENT_PACKAGE)) {
            return true;
        }

        var module = ProtocolManager.moduleByModuleId(it.module());
        if (module.getName().equals(NET_COMMON_PACKAGE) || module.getName().equals(NET_ATTACHMENT_PACKAGE)) {
            return true;
        }
        return false;
    };


    // -----------------------------------------------------------------------------------------------------------------

    public static int localVariableId = 0;

    public static StringBuilder addTab(StringBuilder builder, int deep) {
        builder.append(TAB.repeat(Math.max(0, deep)));
        return builder;
    }

    public static StringBuilder addTabWith2Space(StringBuilder builder, int deep) {
        builder.append(SPACE.repeat(Math.max(0, deep * 2)));
        return builder;
    }

    public static StringBuilder addTabAscii(StringBuilder builder, int deep) {
        builder.append(TAB_ASCII.repeat(Math.max(0, deep)));
        return builder;
    }

    /**
     * Add a number of Tab characters to each line
     */
    public static String addTabs(String str, int deep) {
        if (StringUtils.isEmpty(str)) {
            return str;
        }
        var splits = str.split(FileUtils.LS_REGEX);
        var builder = new StringBuilder();
        for (var split : splits) {
            builder.append(TAB.repeat(Math.max(0, deep)));
            builder.append(split).append(FileUtils.LS);
        }
        return builder.toString();
    }


    /**
     * EN: Generate protocol files to various languages
     * Generate protocol files for all target languages
     */
    public static void generate(GenerateOperation generateOperation) throws IOException, ClassNotFoundException {
        var protocols = ProtocolManager.protocols;

        // Return immediately if there are no protocols to generate
        if (generateOperation.getGenerateLanguages().isEmpty()) {
            return;
        }

        // Outer-layer protocols to generate
        var outsideGenerateProtocols = Arrays.stream(protocols)
                .filter(it -> Objects.nonNull(it))
                .filter(it -> generateProtocolFilter.test(it))
                .toList();

        // Sub-protocols to generate, because the outer protocol references other protocols
        var insideGenerateProtocols = outsideGenerateProtocols.stream()
                .map(it -> ProtocolAnalysis.getAllSubProtocolIds(it.protocolId()))
                .flatMap(it -> it.stream())
                .map(it -> protocols[it])
                .distinct()
                .toList();

        var allGenerateProtocols = new HashSet<IProtocolRegistration>();
        allGenerateProtocols.addAll(outsideGenerateProtocols);
        allGenerateProtocols.addAll(insideGenerateProtocols);

        // Sort by protocol ID in ascending order
        var generateProtocols = allGenerateProtocols.stream()
                .sorted((a, b) -> a.protocolId() - b.protocolId())
                .map(it -> (ProtocolRegistration) it)
                .toList();

        // Parse protocol documentation comments
        GenerateProtocolNote.initProtocolNote(generateProtocols);
        // Compute the output path for the protocol
        GenerateProtocolPath.initProtocolPath(generateProtocols);

        for (var language : generateOperation.getGenerateLanguages()) {
            var codeGenerate = ReflectionUtils.newInstance(language.codeGenerateClass);
            codeGenerate.init(generateOperation);
            if (generateOperation.isMergeProtocol()) {
                codeGenerate.mergerProtocol(generateProtocols);
            } else if (generateOperation.isFoldProtocol()) {
                codeGenerate.foldProtocol(generateProtocols);
            } else {
                codeGenerate.defaultProtocol(generateProtocols);
            }
        }

        // Reserved parameter; may be used in the future, e.g., to change a file extension for Lua
        var protocolParam = generateOperation.getProtocolParam();

        GenerateProtocolNote.clear();
        GenerateProtocolPath.clear();
    }


    public static int indexOf(Field[] fields, Field field) {
        for (int index = 0; index < fields.length; index++) {
            if (fields[index].equals(field)) {
                return index;
            }
        }
        throw new UnknownException();
    }

    // Generate sub-protocols first
    public static List<ProtocolRegistration> subProtocolFirst(List<ProtocolRegistration> registrations) {
        var registrations1 = new ArrayList<ProtocolRegistration>(registrations);
        var subFirstRegistrations = new ArrayList<ProtocolRegistration>();
        var set = new HashSet<Short>();
        while (!registrations1.isEmpty()) {
            for (var i = 0; i < registrations1.size(); i++) {
                var registration = registrations1.get(i);
                var protocolId = registration.protocolId();
                var subProtocols = ProtocolAnalysis.getAllSubProtocolIds(protocolId);
                subProtocols.removeAll(set);
                if (CollectionUtils.isEmpty(subProtocols)) {
                    subFirstRegistrations.add(registration);
                    set.add(protocolId);
                    registrations1.remove(registration);
                    break;
                }
            }
        }
        return subFirstRegistrations;
    }

}
